import type { Art } from '../pixels';
import type { ObstacleId } from '../obstacles';

/** 障害物の絵。黒い溶岩の岩と湯気の出る岩だけは、色の表に無い黒と赤茶を pal で足す */
export const OBSTACLE_ART: Record<ObstacleId, Art> = {
  boulder: {
    w: 42,
    h: 32,
    frames: [
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '....................kkkkkk................',
        '................kkkkLLLLLLkkkkk...........',
        '..............kkLLllllllllLLLLskk.........',
        '.............kLLllllllllllllLLLLskk.......',
        '............ksLLllllllllllllLLLLsssk......',
        '........kkkkssLLLLllllllllLLLLLLssssk.....',
        '......kkLLLLssssLLLLLLLLLLLLLLssLssssk....',
        '.....kLlllllLLssssswLLLLLLsssssssLssssk...',
        '....kLLlllllLLLsswwssssssssssssssssssssk..',
        '....ksLLLLLLLLsswsssssssssssssssssssLssk..',
        '...kssssLLLLssssssssssssssssssssssssssssk.',
        '..ksssswssssssssssssssssssssssSsssssssssk.',
        '..kssswssssssssssssssssssssssssSSsssssssk.',
        '..kssssssssssssssssssssssssssssssSssssssk.',
        '..ksssssssssssssssssssssssssssssssssssssk.',
        '..kssssssssssssssssssssssssssssssssssssSk.',
        '..kssssssssssssssssssSsssssssssssssssssk..',
        '..ksssssssssssSsssssssSsssssssssssssSSsk..',
        '..ksSSsssssssssSsssssssssssssssssssSSSSk..',
        '..kSSSSssssssssssssssssssssssssssSSSSSSk..',
        '..kSSSSSSSSSSSSSSssssssssssssssSSSSSSSk...',
        '...kSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSk....',
        '....kkSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSk.....',
        '......kkkkkkkkkSSSSSSSSSSSSSSSSSSkkk......',
        '...............kkkkkkkkkkkkkkkkkk.........',
        '..........................................'
      ]
    ]
  },
  log: {
    w: 48,
    h: 26,
    frames: [
      [
        '................................................',
        '................................................',
        '................................................',
        '................................................',
        '..........................kk....................',
        '.........................krrk...................',
        '.........kkkkkkkkkkkkkk..krwk...................',
        '...kkkkkkLllllllllllLLLkkkcckkkkkkkkkkkkkkkk....',
        '..ktttttLLllllllllllLLLLtttLLLLLLLLtttcccccck...',
        '.ktttttttLLLLLLLLLLLLLLttttLLLLLLLLtttcccccck...',
        '.ktttttttttttttttttttttttttttttttttttccbbbbcck..',
        'ktttttttttttttttttttttttttttttttttttcccbbbbccck.',
        'ktttttttTTttttTTtttttTTttttTTttttTTtccbbccbbcck.',
        'ktttttttttTtttttTttttttTtttttTtttttTccbccccbcck.',
        'ktttttttttttttttttBtttttttttttttttttccbcbbcbcck.',
        'ktttttttttBBttttttttttttttttttttttttccbccccbcck.',
        'ktttttttttttttttttttttttBBBtttttttttccbbccbbcck.',
        'kTttTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTcccbbbbccbk.',
        '.kttTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTccbbbbcbk..',
        '.kTtTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTcccccck...',
        '..kTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTbbbbbbk...',
        '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
        '................................................',
        '................................................',
        '................................................',
        '................................................'
      ]
    ]
  },
  bigTomb: {
    w: 30,
    h: 38,
    frames: [
      [
        '..............................',
        '...........kkkkkkk............',
        '........kkkssssssskkk.........',
        '.......ksssssssssssssk........',
        '......ksssqssssssssssk........',
        '.....ksssqsssssssssssk........',
        '....ksssqsssssssssssssk.......',
        '....ksssssssssssssssssskk.....',
        '....ksssssssssssssssGssssk....',
        '....kssssssssssssssGsssssk....',
        '....kssqssssssSSssssGssssk....',
        '....kssqssssssSSsssGsssssk....',
        '....kssqssssssSSsssssssssk....',
        '....kssqssssssSSsssssssssk....',
        '....kssqssSSSSSSSSSSsssssk....',
        '....kssqssSSSSSSSSSSsssssk....',
        '....kssqssssssSSsssssssssk....',
        '....kssqssssssSSsssssssssk....',
        '....kssqssssssSSsssssssssk....',
        '....ksssssssssSSsssssssssk....',
        '....ksssssssssSSsssssssssk....',
        '....ksssssssssSSsssssssssk....',
        '....ksssssssssSSsssssssssk....',
        '....kssssssssssssssssssssk....',
        '....kssssssssssssssssssssk....',
        '....ksssssGssssssssssssssk....',
        '....kssssssGsssssssssssssk....',
        '....kssssGsssssssssssssssk....',
        '....kSSSSSSSSSSSSSSSSSSSSk....',
        '....kSSSSSSSSSSSSSSSSSSSSk....',
        '.kkkLSSSSSSSSLSSSSSSSSSSSLkkk.',
        'kMMLMMLMMMMMLMMMMMMMMMMMMMLMMk',
        'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',
        'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',
        'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
        '.kkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
        '..............................',
        '..............................'
      ]
    ]
  },
  fence: {
    w: 48,
    h: 30,
    frames: [
      [
        '................................................',
        '.kkkkkkkkk......................................',
        'kqqqqqqqqqk.k....k....k....k....k...............',
        'kqqqqqqqqqkknk..knk..knk..knk..knk..............',
        'ksqqqqqqqsknnk.knnk.knnk.knnk.knnk..............',
        '.kssssssskknnNkknnNkknnNkknnNkknnNk.............',
        '.ksqssssskknnk.knnk.knnk.knnk.knnk..............',
        '.ksqssssskknnk.knnk.knnk.knnk.knnk..............',
        '.ksqssssskknnkkknnkkknnkkknnkkknnkkk............',
        '.ksqsssssnnnnnnnnnnnnnnnnnnnnnnnnnnnk....kk.....',
        '.ksssssssNNnnNNNnnNNNnnNNNnnNNNnnNNnk...kssk....',
        '.kssssssskknnkkknnkkknnkkknnkkknnkknnk.kssssk...',
        '.kssssSsskknnk.knnk.knnk.knnk.knnkkNnkkssssssk..',
        '.ksssSssskknnk.knnk.knnk.knnk.knnk.knnksssssssk.',
        '.kssssSsskknnk.knnk.knnk.knnk.knnk.kNnksssssssk.',
        '.kssssssskknnk.knnk.knnk.knnk.knnk..kNnsqsssssk.',
        '.kssssssskknnk.knnk.knnk.knnk.knnk...knsqsssssk.',
        '.kssssssskknnk.knnk.knnk.knnk.knnk...kNsqsssssk.',
        '.kssssssskknnkkknnkkknnkkknnkkknnkkkk.kssssSssk.',
        '.ksssssssnnnnnnnnnnnnnnnnnnnnnnnnnnnnkksssSsssk.',
        '.ksssssssNNnnNNNnnNNNnnNNNnnNNNnnNNNNkksssssssk.',
        '.kssssssskknnkkknnkkknnkkknnkkknnkkkk.ksssssssk.',
        '.kssssssskknnk.knnk.knnk.knnk.knnk....ksssssssk.',
        '.kSSSSSSSkknnk.knnk.knnk.knnk.knnk..kkkSSSSSSSk.',
        '.kSSSSSSSkkNNk.kNNk.kNNk.kNNk.kNNk.ksskSSSSSSSk.',
        '.kSSSSSSSk.kk...kk...kk...kk...kk.kssssSSSSSSSkk',
        '..kkkkkkk.........................kSssSkkkkkssss',
        '...................................kSSk....kSSSS',
        '....................................kk......kkkk',
        '................................................'
      ]
    ]
  },
  icy: {
    w: 40,
    h: 36,
    frames: [
      [
        '........................................',
        '........................................',
        '........................................',
        '........................................',
        '.................kk.....................',
        '................kjik....................',
        '................kjik....................',
        '................kjik....................',
        '................kwjik...................',
        '................kwjik...................',
        '...............kjjjik...................',
        '...............kjjjiik......kk..........',
        '...............kwjjiik.....kJIk.........',
        '.........k.....kwjjiik.....kJIk.........',
        '........kIk...kjjjjiik.....kJIk.........',
        '........kIk...kjjjjiiik...kJwJk.........',
        '.......kJJk...kjjjjiiik...kJwJIk........',
        '.......kJJIk..kjjjjjiik...kJJJIk........',
        '.......kwJIk..kjjjjjiiik.kJJJJIk........',
        '.......kwJIk.kjjjjjjiiik.kJJJJIk........',
        '.......kJJIIkkjjjjjjiiik.kJJJJIIk.k.....',
        '......kJJJIIkkjjjjjjiiik.kJJJJIIkkjk....',
        '......kJJJJIkkjjjjjjiiiikJJJJJIIkkjjk...',
        '......kJJJJIIjjjjjjjiiiikJJJJJIIkjjjk...',
        '......kJJJJIIjjjjjjjiiiikJJJJJIIIjwjk...',
        '......kJJJJIIjjjjjjjiiiiiJJJJJJIIjjjk...',
        '......kJJJJIIIjjjjjjjiiiiJJJJJJIIjjjjk..',
        '.....kJJJJJiiiiiiiiiiiiiiiiiiJJIIjjjjk..',
        '...kkkiiiiiwwwwwwwwwwwwwwiiiiiiiiijjjk..',
        '..kiiiwwwwwwwwwwwwwwwwwwwwwwwwiiiiiiijk.',
        '.kiiiwwwwwwwwwwwwwwwwwwwwwwwwwwiiiiiiik.',
        '.kIiiiwwwwwwwwwwwwwwwwwwwwwwwwiiiiiiiIk.',
        '..kIIIiiiiiwwwwwwwwwwwwwwiiiiiiiiiIIIk..',
        '...kkkIIIIIiiiiiiiiiiiiiiiiiiIIIIIkkk...',
        '......kkkkkIIIIIIIIIIIIIIIIIIkkkkk......',
        '...........kkkkkkkkkkkkkkkkkk...........'
      ]
    ]
  },
  snowTree: {
    w: 36,
    h: 42,
    frames: [
      [
        '....................................',
        '....................................',
        '.................kk.................',
        '................kiik................',
        '...............kiwiik...............',
        '..............kiwiiik...............',
        '..............kiiddiik..............',
        '.............kidddddiik.............',
        '............kIddddddddIk............',
        '.............kdddiidddk.............',
        '............kdddiiiidddk............',
        '...........kdddiiiiiidddk...........',
        '...........kddiiiiiiiildk...........',
        '..........kDdiwiiiiiiiilDk..........',
        '...........kiwddiiidddiIk...........',
        '...........kdddddddddddk............',
        '...........kddddddddddddk...........',
        '..........kddddddiiddddddk..........',
        '.........kddddddiiiiddddddk.........',
        '........kdddddiiiiiiiidddddk........',
        '.......kdddddiiiiiiiiiidddldk.......',
        '......kDDDdiiiiiiiiiiiiiidDlDk......',
        '.......kkkwiiiiiiiiiiiiiiIkkk.......',
        '.......kIwiiidddddiiiidddkIIk.......',
        '......kIkkddddddddddddddddkk........',
        '.......kkddddddddddddddddddk........',
        '.......kddddddddddddddddddddk.......',
        '......kdddddddddddddlddddddddk......',
        '.....kdddddddddddddddlddddddddk.....',
        '....kddiddddddddddddddddddddiddk....',
        '...kDIIDDDDDDDDDddddDDDDDDDDDIIDk...',
        '....kkkkkkkkkkkkTTTTkkkkkkkkkkkk....',
        '........kkkkkkkkTTTTkkkkkkkk........',
        '.....kkkiiiiiiiiiiiiiiiiiiiikkk.....',
        '...kkiiwwwwwwwwwwwwwwwwwwiiiiiikk...',
        '..kiiwwwwwwwwwwwwwwwwwwwwwwiiiiiik..',
        '.kiiiwwwwwwwwwwwwwwwwwwwwwwiiiiiiik.',
        '.kIiiiiwwwwwwwwwwwwwwwwwwiiiiiiiiIk.',
        '..kIIiiiiiiiiiiiiiiiiiiiiiiiiiiIIk..',
        '...kkIIIiiiiiiiiiiiiiiiiiiiiIIIkk...',
        '.....kkkIIIIIIIIIIIIIIIIIIIIkkk.....',
        '........kkkkkkkkkkkkkkkkkkkk........'
      ]
    ]
  },
  lavaRock: {
    w: 42,
    h: 32,
    frames: [
      [
        '..........................................',
        '..........................................',
        '..........................................',
        '..........................................',
        '....................kkkk..................',
        '.................kkkxxxxkk................',
        '..............kkkxxxxxxxxakkk.............',
        '............kkxxxxxxxxxaaaaaakk...........',
        '...........kaaxxxxxxxaaaaaaaaaak..........',
        '..........kaaaaxxxxxaaaaaaaaaaaak.........',
        '.........kaaxaaaxxaaaaaaaaaaaaaaak........',
        '........kaaxaaaaaaaaaaaaaaaaaaaaaak.......',
        '.......kaaaaaaaaaaaaaaaaaaaaaoaaaaak......',
        '......kaaaaaaaoaaaaaaaaaaaaaaoaaaaaak.....',
        '.....kaaaaaaaaaoaaaaaaaaaaaaaayaaaaxak....',
        '.....kaaxaaaaaaaoaaaaaaaaaaaaayaaaaaaak...',
        '.....kaaaaaaaaaayaaaaaaaaaaaaaooaaaaaak...',
        '....kaaaaaaaaaaaayaaooaaaaaaaaaaoaaaaak...',
        '....kaaaaaaaaaaaaayoaaaaaaaaaaaaaaaaaak...',
        '....kaaaaoaaaaaaaaoaaaaaaaaaaaaaaaaaaaak..',
        '....kaaaaaoaaaaaaoaaaaaaaaaaaaaaaaaaaaak..',
        '...kaaaaaaaraaaaraaaaaaaaaaaaaaaaaaaaaak..',
        '...kaAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAk.',
        '...kAAAAAAAAAAAAAAAAAAAAArArAAAAAAAAAAAAk.',
        '...kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk.',
        '..kaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk.',
        '..kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk.',
        '..kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk.',
        '..kkkkkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkkkkk.',
        '...kkkkkkkkkkkkkkkkkkAkkkkkkkkkkkkkkkkkk..',
        '.......kkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
        '.....................k....................'
      ]
    ],
    pal: { a: '#3b3537', A: '#24201f', x: '#5a5355' }
  },
  steamRock: {
    w: 36,
    h: 40,
    frames: [
      [
        '....................................',
        '.................qqqq...............',
        '...............qwwwwwqq.............',
        '...............wwwwwwqq.............',
        '...............qwwwwwqq.............',
        '...............qqqqqqqq.............',
        '.................qqqq...............',
        '...............qqqq.................',
        '..............wwwwwq................',
        '.............qwwwwwqq...............',
        '.............qwwwwqqq...............',
        '..............qqqqqq................',
        '...............qqqqq................',
        '.................wwwq...............',
        '................qwwwqq..............',
        '................qwwwqq..............',
        '.................qqqq...............',
        '................qqqq................',
        '................wwwq................',
        '................qqqq................',
        '.............kkkkkkkkkk.............',
        '..........kkkffAAAAAAeekk...........',
        '........kkffffAkrokokAeeekk.........',
        '.......kefffffeAAAoAreeeeeek........',
        '......keeefffeeeeeeeeeeeeeeek.......',
        '.....keeeeefeeeeeeeeeeeeeeeeek......',
        '....keeeeeeeeeeeeeeeeeeeEeeeeek.....',
        '...keeeeeeeeeeeeeeeeeeeeeEeeeeek....',
        '...keeeeeeeeeeeeeeeeeeeeeEeeeeeek...',
        '...keeeeeeeEeeeeeeeeeeeeeeEeeeeeek..',
        '...keeeeeeeeEeeeeeeeeeeeEeeeeeeeek..',
        '...keeeeeeeeEeeeeeeeeeeeeEEeeeeeek..',
        '..kEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEk..',
        '..kEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEk..',
        '..kEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEk..',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...',
        '....................................',
        '....................................',
        '....................................'
      ],
      [
        '....................................',
        '...............qqqq.................',
        '.............qwwwwwqq...............',
        '.............wwwwwwqq...............',
        '.............qwwwwwqq...............',
        '.............qqqqqqqq...............',
        '...............qqqq.................',
        '.................qqqq...............',
        '................wwwwwq..............',
        '...............qwwwwwqq.............',
        '...............qwwwwqqq.............',
        '................qqqqqq..............',
        '................qqqqq...............',
        '..............qwwwqq................',
        '..............wwwwqq................',
        '..............qwwwqq................',
        '..............qqqqqq................',
        '................qwqq................',
        '...............qwwwqq...............',
        '...............qqqqqq...............',
        '.............kkkkkkkkkk.............',
        '..........kkkffAAAAAAeekk...........',
        '........kkffffAkrokokAeeekk.........',
        '.......kefffffeAAAoAreeeeeek........',
        '......keeefffeeeeeeeeeeeeeeek.......',
        '.....keeeeefeeeeeeeeeeeeeeeeek......',
        '....keeeeeeeeeeeeeeeeeeeEeeeeek.....',
        '...keeeeeeeeeeeeeeeeeeeeeEeeeeek....',
        '...keeeeeeeeeeeeeeeeeeeeeEeeeeeek...',
        '...keeeeeeeEeeeeeeeeeeeeeeEeeeeeek..',
        '...keeeeeeeeEeeeeeeeeeeeEeeeeeeeek..',
        '...keeeeeeeeEeeeeeeeeeeeeEEeeeeeek..',
        '..kEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEk..',
        '..kEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEk..',
        '..kEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEk..',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
        '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...',
        '....................................',
        '....................................',
        '....................................'
      ]
    ],
    pal: { A: '#24201f', e: '#7c5a50', E: '#4c3530', f: '#a8857a' }
  }
};
